# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54c9457a58ddec0cada647eb7f0ad23a8e04110f8f0836c8df024e7f186f8b692cdd5b6ea7d15ed1f72a37a16559b4560b3bcda1a56a0a16634dfc79d85dd474

test:
  secret_key_base: c66563bde62894a37a20f9b2625934cc1853a584b2f7007da4c0fab44f72586c199e59f674bed10b56785099888e5fbae0e72b55b9e2fe26aa73b8218b69efc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
